
export const CATIGORIES_ACTION_TYPES = {

    "FETCH_CATEGORIES_START": "FETCH_CATEGORIES_START",
    "FETCH_CATEGORIES_SUCSSES": "FETCH_CATEGORIES_SUCSSES",
    "FETCH_CATEGORIES_FAILED": "FETCH_CATEGORIES_FAILED",
}